### ISSUE TITLE
reconnect after lost connection

### ISSUE THREAD

**Issue by Nightwelf** [flutterjanus/flutter_janus_client#77] opened 2022-07-19 12:55 UTC
Hi! I need reconnect to all text rooms after lost connection or after connection was refused. Please. help. How i can do it?

**Comment by shivanshtalwar0** [comment] 2022-07-19 16:49
For this you can use connectivity package to see if connectionstate got disconnected in that event you can use saved user info to connect user back to room if connection is back on, i hope this solves your issue
Closing for now you can reopen if you find bug in package itself

**Comment by Nightwelf** [comment] 2022-07-19 16:51
after reconnect i must dispose all?

**Comment by shivanshtalwar0** [comment] 2022-07-19 16:54
Well it would be better idea to recreate new session instance and then attach the plugin on it to make sure everything is working as expected

**Comment by shivanshtalwar0** [comment] 2022-07-19 16:56
You know what i will add it in my todo list using connectivity package and add auto reconnect in the event of disconnected network state

**Comment by shivanshtalwar0** [comment] 2022-07-19 16:57
For the time being you can use the approach i told you

**Comment by Nightwelf** [comment] 2022-07-19 16:58
very often the socket crashes on its own. what to do in this case? while my server is working properly. the socket may just fall

**Comment by shivanshtalwar0** [comment] 2022-07-19 16:59
I don't believe it would crash on its own unless network state has been changed

**Comment by Nightwelf** [comment] 2022-07-19 17:01
Maybe it's my mistake. I try to research. Thanks!

**Comment by shivanshtalwar0** [comment] 2024-01-29 00:08
closing as it is not planned, it is not that urgent anyway maybe i will revisit it as an enhancement in future

**Closed by shivanshtalwar0** 2024-01-29 00:08 UTC

**Comment by YazanFarrah** [comment] 2025-10-22 10:59
> closing as it is not planned, it is not that urgent anyway maybe i will revisit it as an enhancement in future

I think this is worth looking into, reconnecting after network loss is quite important for production use cases, especially for maintaining call/session stability. It would be great to keep this open for future consideration or community contributions. WDYT?

**Comment by shivanshtalwar0** [comment] 2025-10-22 13:40
@YazanFarrah The problem is once there is network disconnection library being a generic entity can't anticipate which plugin was used and what kind of webrtc wiring was done to attempt reconnecting therefore i believe it's the responsibility of the user of library to implement reconnection logic in the app itself something like below
Ongoing videoroom => internet off => internet on after 30seconds => app should retry connection with fresh instance of janussession and this would work just fine 
If you have another idea about this i am all ears

**Comment by YazanFarrah** [comment] 2025-10-22 14:44
Just to confirm, you mean after network recovery, I should recreate a fresh Janus session and plugin instance (instead of trying to reuse the old one), right?

**Comment by shivanshtalwar0** [comment] 2025-10-25 21:03
sure! also i am writing a detailed book covering webrtc,janus,typed_janus_js,flutter_janus_client and full voip app development i will post link to purchase it on README.md you can consider purchasing it if you feel like.

<img width="502" height="756" alt="Image" src="https://github.com/user-attachments/assets/b0f14911-820d-4bd3-9a11-f05b6bba0d71" />
