### ISSUE TITLE
issue:- android to ios video call issue with don’t hear the other person voice on the call

### ISSUE THREAD

**Issue by RRohitM** [flutterjanus/flutter_janus_client#65] opened 2022-04-07 06:57 UTC
You don’t hear the other person speaking at all in a video call. I tested video calls from iOS phone to Android phone and vice versa but don’t hear the other person on the call. On the other hand, the test was successful on one Android to an Android phone, though on some other android phones the sound was not working also.

**Comment by nikohpng** [comment] 2022-04-12 13:39
> I will test it out and get back to you guys.

Thank for your reply. I use janus-gateway-0.11.8. 
I've found out what the problem is. I noticed that gateway didn't reply to streams. such as
```dart
plugin.typedMessages?.listen((event) async {
      Object data = event.event.plugindata?.data;
      if (data is VideoRoomJoinedEvent) {
        (await plugin.publishMedia(bitrate: 3000000));
        List<Map<String, dynamic>> publisherStreams = [];
        for (Publishers publisher in data.publishers ?? []) {
          for (Streams stream in publisher.streams ?? []) {
            feedStreams[publisher.id!] = {
              "id": publisher.id,
              "display": publisher.display,
              "streams": publisher.streams
            };
            publisherStreams.add({"feed": publisher.id, ...stream.toJson()});
            if (publisher.id != null && stream.mid != null) {
              subStreams[stream.mid!] = publisher.id!;
              print("substreams is:");
              print(subStreams);
            }
          }
        }
        subscribeTo(publisherStreams);
      }
```
because of the publisher streams，the subscribeTo function return directly!

**Comment by CoMatu** [comment] 2022-07-20 09:11
I have some issue...

**Comment by MeshariSuliman** [comment] 2022-08-20 14:20
add   Function(MediaStream stream)? onAddRemoteStream;

init state 
    onAddRemoteStream = ((stream) {
      remoteRenderer.srcObject = stream;
      setState(() {});
    });

create call alse join call 
    peerConnection.onAddStream = (MediaStream stream) {
      print("Add remote stream");
      onAddRemoteStream?.call(stream);
      remoteStream = stream;
      setState(() {});
    };

**Comment by shivanshtalwar0** [comment] 2022-09-05 06:03
Can you guys test video call plugin now? i made some fixes

**Comment by shivanshtalwar0** [comment] 2022-10-17 08:46
closing now hopefully this issue must be resolved for you guys!

**Closed by shivanshtalwar0** 2022-10-17 08:46 UTC
